import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import Footer from "@/components/footer";
import Navbar2 from "@/components/navbar2";
import Partners from "@/components/partners";
import Nav2 from "@/components/navbar2";
import SmoothScrolling from "@/components/SmoothScrolling";
import { K2D } from 'next/font/google'
import Navbara from "@/components/test";
const inter = Inter({ subsets: ["latin"] });
const k2d = K2D({
  weight: ['400','700', '600'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Mak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={k2d.className + " bg-stone-800 scroll-smooth"}>
        <Nav2/>
        {children}

        <Footer />
      </body>
    </html>
  );
}
